FROM balenalib/%%BALENA_ARCH%%-debian-node:10.15-latest-build
WORKDIR /usr/src/app
COPY . .
RUN sudo apt update && sudo apt install \
  zip \
  apt-transport-https \
  unzip \
  screen \
  vim
RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn
RUN sudo ./build-server.sh 1
CMD ["/bin/bash", "./start.sh"]
